// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-PdLDY9q5v8VyRF1oSZ40XOpL-JeB-Q',
    appId: '1:609360431324:web:371e1f3e64c11d2bf48c19',
    messagingSenderId: '609360431324',
    projectId: 'rescue-app-6804e',
    authDomain: 'rescue-app-6804e.firebaseapp.com',
    storageBucket: 'rescue-app-6804e.appspot.com',
    measurementId: 'G-W1N6WK25RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-MJr4W33e_tnDj0RWeW63BIoR6AeO1o',
    appId: '1:609360431324:android:b5845a04dac14913f48c19',
    messagingSenderId: '609360431324',
    projectId: 'rescue-app-6804e',
    storageBucket: 'rescue-app-6804e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe7Pf9ErhCQ233HE75_3JkNGX8VcTRei4',
    appId: '1:609360431324:ios:77c9a97342189c05f48c19',
    messagingSenderId: '609360431324',
    projectId: 'rescue-app-6804e',
    storageBucket: 'rescue-app-6804e.appspot.com',
    androidClientId: '609360431324-494jkroftk4n5fpjpmgdglve1e8sbf5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ralert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe7Pf9ErhCQ233HE75_3JkNGX8VcTRei4',
    appId: '1:609360431324:ios:89a924b72e506415f48c19',
    messagingSenderId: '609360431324',
    projectId: 'rescue-app-6804e',
    storageBucket: 'rescue-app-6804e.appspot.com',
    androidClientId: '609360431324-494jkroftk4n5fpjpmgdglve1e8sbf5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ralert.RunnerTests',
  );
}
